CREATE SEQUENCE patient_id_seq;

CREATE TABLE PAZIENTE (
    ID SMALLINT NOT NULL DEFAULT nextval('patient_id_seq') PRIMARY KEY,
    CODICE_FISCALE	VARCHAR,
    DATA_INSERIMENTO TIMESTAMP,
    COGNOME	VARCHAR,
    NOME VARCHAR,
    GLICOGENOSI VARCHAR NOT NULL,
    DATA_NASCITA TIMESTAMP,
    ETA INTEGER,
    OSPEDALE VARCHAR,
    OSPEDALE_INFUZIONE VARCHAR,
    GENITORI VARCHAR,
    FIGLI VARCHAR,
    DATI_CORRETTI VARCHAR,
    PRESSO VARCHAR,
    QA_2016 VARCHAR,
    QA_2017 VARCHAR,
    QA_2018 VARCHAR,
    NOTE OID
);

ALTER SEQUENCE patient_id_seq OWNED BY PAZIENTE.ID;
