CREATE SEQUENCE address_id_seq;

CREATE TABLE INDIRIZZO (
    ID SMALLINT NOT NULL DEFAULT nextval('address_id_seq') PRIMARY KEY,
    VIA VARCHAR NOT NULL,
    CITTA VARCHAR NOT NULL,
    CAP VARCHAR NOT NULL,
    PROV VARCHAR NOT NULL,
    INDIRIZZO_SPEDIZIONE VARCHAR,
    NOME_REGIONE VARCHAR NOT NULL,
    NAZIONE VARCHAR NOT NULL,
    EMAIL VARCHAR,
    TELEFONO VARCHAR,
    CELLULARE VARCHAR
);

ALTER SEQUENCE address_id_seq OWNED BY INDIRIZZO.ID;

ALTER TABLE PAZIENTE ADD COLUMN REF_INDIRIZZO bigint;
ALTER TABLE PAZIENTE ADD CONSTRAINT FK_INDIRIZZO FOREIGN KEY (REF_INDIRIZZO) REFERENCES INDIRIZZO;

