CREATE SEQUENCE file_upload_id_seq;

CREATE TABLE FILE_UPLOAD (
    ID SMALLINT NOT NULL DEFAULT nextval('file_upload_id_seq') PRIMARY KEY,
    NOME_FILE VARCHAR NOT NULL,
    CATEGORIA VARCHAR NOT NULL,
    DATAORA_CARICAMENTO TIMESTAMP NOT NULL,
    FILE OID NOT NULL
);

ALTER SEQUENCE file_upload_id_seq OWNED BY FILE_UPLOAD.ID;