CREATE SEQUENCE account_id_seq;

CREATE TABLE ACCOUNT (
    ID SMALLINT NOT NULL DEFAULT nextval('account_id_seq') PRIMARY KEY,
    NOME_UTENTE VARCHAR NOT NULL,
    PASSWORD VARCHAR NOT NULL,
    RUOLO VARCHAR NOT NULL,
    CREATO_IL TIMESTAMP
);

ALTER TABLE ACCOUNT ADD CONSTRAINT ACCT_U_CONSTRAINT UNIQUE (NOME_UTENTE);

ALTER SEQUENCE account_id_seq OWNED BY ACCOUNT.ID;